#!/usr/bin/env python3
"""
SPX Puppet — Complete Install
Adds: SPXMotionImporter, VideoMocapPanel, FaceMocapPanel,
      2D Style Presets, Puppet2DExportPanel
Run from: /workspaces/SPX-Puppet
python3 install_puppet_complete.py && npm run build && git add -A && git commit -m "feat: motion import, video mocap, face mocap, 2D style export" && git push
"""
import os, re

REPO = "/workspaces/SPX-Puppet"
SRC  = f"{REPO}/src"
COMP = f"{SRC}/components"
PIPE = f"{SRC}/pipeline"
MOCAP= f"{COMP}/mocap"
for d in [PIPE, MOCAP]: os.makedirs(d, exist_ok=True)

FILES = {}

# ════════════════════════════════════════════════════════════
# 1. SPXMOTION IMPORTER
# ════════════════════════════════════════════════════════════
FILES[f"{PIPE}/SPXMotionImporter.js"] = r"""
/**
 * SPXMotionImporter — SPX Puppet
 * Loads .spxmotion files and drives puppet bone keyframes
 * .spxmotion is generated by SPX Mesh Editor's ExportToPuppetButton
 */
export class SPXMotionImporter {
  constructor() {
    this.motion=null; this.playing=false; this.startTime=null;
    this.onFrame=null; this.onComplete=null; this._raf=null;
  }

  async loadFromFile(file) {
    return new Promise((resolve,reject)=>{
      const r=new FileReader();
      r.onload=e=>{
        try{ const d=JSON.parse(e.target.result); this.load(d); resolve(d); }
        catch(err){ reject(new Error('Invalid .spxmotion: '+err.message)); }
      };
      r.onerror=()=>reject(new Error('File read error'));
      r.readAsText(file);
    });
  }

  load(data) {
    if(data.format!=='spxmotion') throw new Error('Not a .spxmotion file');
    this.motion=data; this.playing=false;
    this._raf&&cancelAnimationFrame(this._raf);
  }

  getFrameAt(time) {
    if(!this.motion) return {};
    const {frames,duration}=this.motion;
    const t=((time%duration)+duration)%duration;
    let lo=0,hi=frames.length-1;
    while(lo<hi-1){ const mid=(lo+hi)>>1; if(frames[mid].time<=t) lo=mid; else hi=mid; }
    const fA=frames[lo], fB=frames[Math.min(hi,frames.length-1)];
    if(!fB||fA===fB) return{...fA.keyframes};
    const span=fB.time-fA.time, alpha=span>0?(t-fA.time)/span:0;
    const result={};
    this.motion.bones.forEach(bone=>{
      const a=fA.keyframes[bone]||{}, b=fB.keyframes[bone]||{};
      result[bone]={
        x:       lerp(a.x||0,      b.x||0,      alpha),
        y:       lerp(a.y||0,      b.y||0,      alpha),
        rotation:lerpAngle(a.rotation||0, b.rotation||0, alpha),
        scale:   lerp(a.scale||1,  b.scale||1,  alpha),
      };
    });
    return result;
  }

  play(onFrame,onComplete) {
    if(!this.motion) return;
    this.onFrame=onFrame||this.onFrame;
    this.onComplete=onComplete||this.onComplete;
    this.playing=true; this.startTime=performance.now();
    const tick=(now)=>{
      if(!this.playing) return;
      const elapsed=(now-this.startTime)/1000;
      this.onFrame&&this.onFrame(this.getFrameAt(elapsed),elapsed);
      if(elapsed>=this.motion.duration){ this.playing=false; this.onComplete&&this.onComplete(); return; }
      this._raf=requestAnimationFrame(tick);
    };
    this._raf=requestAnimationFrame(tick);
  }

  loop(onFrame) {
    if(!this.motion) return;
    this.onFrame=onFrame; this.playing=true; this.startTime=performance.now();
    const tick=(now)=>{
      if(!this.playing) return;
      const elapsed=(now-this.startTime)/1000;
      this.onFrame&&this.onFrame(this.getFrameAt(elapsed),elapsed);
      this._raf=requestAnimationFrame(tick);
    };
    this._raf=requestAnimationFrame(tick);
  }

  stop(){ this.playing=false; this._raf&&cancelAnimationFrame(this._raf); }
  get duration(){ return this.motion?.duration||0; }
  get fps()     { return this.motion?.fps||30; }
  get bones()   { return this.motion?.bones||[]; }
  get name()    { return this.motion?.name||''; }
}

function lerp(a,b,t){ return a+(b-a)*t; }
function lerpAngle(a,b,t){ let d=((b-a)%360+540)%360-180; return a+d*t; }
export default SPXMotionImporter;
"""

# ════════════════════════════════════════════════════════════
# 2. VIDEO MOCAP PANEL
# ════════════════════════════════════════════════════════════
FILES[f"{MOCAP}/VideoMocapPanel.jsx"] = r"""
import React, { useState, useRef, useEffect } from 'react';

const T={bg:"#06060f",panel:"#0d0d1a",border:"#1a1a2e",teal:"#00ffc8",orange:"#FF6600",text:"#e0e0e0",muted:"#aaa",font:"JetBrains Mono,monospace"};
const S={
  root:{background:T.bg,color:T.text,fontFamily:T.font,padding:16,height:"100%",overflowY:"auto"},
  h2:{color:T.teal,fontSize:14,marginBottom:12,letterSpacing:1},
  lbl:{fontSize:11,color:T.muted,display:"block",marginBottom:4},
  inp:{width:"100%",background:T.panel,border:"1px solid "+T.border,color:T.text,padding:"4px 8px",borderRadius:4,fontFamily:T.font,fontSize:11,marginBottom:8,boxSizing:"border-box"},
  btn:{background:T.teal,color:T.bg,border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnO:{background:T.orange,color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnRed:{background:"#cc2200",color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  sec:{background:T.panel,border:"1px solid "+T.border,borderRadius:6,padding:12,marginBottom:12},
  stat:{fontSize:11,color:T.teal,marginBottom:4},
  canvas:{width:"100%",borderRadius:6,border:"1px solid "+T.border,background:"#000",display:"block"},
  bar:(p)=>({width:`${p}%`,height:4,background:T.teal,borderRadius:2,transition:"width .2s"}),
};

const POSE_TO_SPX={
  0:"head", 11:"l_shoulder", 12:"r_shoulder", 13:"l_upper_arm", 14:"r_upper_arm",
  15:"l_forearm", 16:"r_forearm", 17:"l_hand", 18:"r_hand",
  23:"l_thigh", 24:"r_thigh", 25:"l_shin", 26:"r_shin", 27:"l_foot", 28:"r_foot",
};

function midpoint(a,b){ return {x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:((a.z||0)+(b.z||0))/2}; }

function landmarksToSPX(lm,w,h){
  const kf={};
  Object.entries(POSE_TO_SPX).forEach(([idx,name])=>{
    const p=lm[+idx]; if(!p) return;
    kf[name]={x:p.x*w, y:p.y*h, rotation:0, scale:1, confidence:p.visibility||1};
  });
  if(lm[23]&&lm[24]){ const hip=midpoint(lm[23],lm[24]); kf.hips={x:hip.x*w,y:hip.y*h,rotation:0,scale:1}; }
  if(lm[11]&&lm[12]&&lm[23]&&lm[24]){ const sp=midpoint(midpoint(lm[11],lm[12]),midpoint(lm[23],lm[24])); kf.spine={x:sp.x*w,y:sp.y*h,rotation:0,scale:1}; }
  return kf;
}

const CONNECTIONS=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];

export default function VideoMocapPanel({ onMotionReady, onLiveFrame }) {
  const [mpReady,setMpReady]=useState(false);
  const [recording,setRecording]=useState(false);
  const [live,setLive]=useState(false);
  const [fps,setFps]=useState(30);
  const [canvasW,setCanvasW]=useState(640);
  const [canvasH,setCanvasH]=useState(480);
  const [progress,setProgress]=useState(0);
  const [frameCount,setFrameCount]=useState(0);
  const [status,setStatus]=useState('');
  const [videoSrc,setVideoSrc]=useState(null);
  const videoRef=useRef(null);
  const canvasRef=useRef(null);
  const poseRef=useRef(null);
  const camRef=useRef(null);
  const recorded=useRef([]);
  const startT=useRef(0);

  useEffect(()=>{
    if(window.Pose){setMpReady(true);return;}
    const s=document.createElement('script');
    s.src='https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js';
    s.crossOrigin='anonymous';
    s.onload=()=>{
      const s2=document.createElement('script');
      s2.src='https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js';
      s2.crossOrigin='anonymous'; s2.onload=()=>setMpReady(true);
      document.head.appendChild(s2);
    };
    document.head.appendChild(s);
  },[]);

  function initPose(videoEl,canvasEl){
    if(!window.Pose){setStatus('MediaPipe not loaded');return null;}
    const pose=new window.Pose({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/pose/${f}`});
    pose.setOptions({modelComplexity:1,smoothLandmarks:true,minDetectionConfidence:0.5,minTrackingConfidence:0.5});
    pose.onResults(results=>{
      const ctx=canvasEl.getContext('2d');
      ctx.clearRect(0,0,canvasEl.width,canvasEl.height);
      ctx.drawImage(results.image,0,0,canvasEl.width,canvasEl.height);
      if(!results.poseLandmarks) return;
      const lm=results.poseLandmarks;
      // Draw skeleton
      ctx.strokeStyle='#00ffc8'; ctx.lineWidth=2;
      CONNECTIONS.forEach(([a,b])=>{
        const pa=lm[a],pb=lm[b]; if(!pa||!pb) return;
        ctx.beginPath();ctx.moveTo(pa.x*canvasEl.width,pa.y*canvasEl.height);
        ctx.lineTo(pb.x*canvasEl.width,pb.y*canvasEl.height);ctx.stroke();
      });
      Object.keys(POSE_TO_SPX).forEach(i=>{
        const p=lm[+i]; if(!p) return;
        ctx.beginPath();ctx.arc(p.x*canvasEl.width,p.y*canvasEl.height,4,0,Math.PI*2);
        ctx.fillStyle='#FF6600';ctx.fill();
      });
      const kf=landmarksToSPX(lm,canvasEl.width,canvasEl.height);
      onLiveFrame&&onLiveFrame(kf);
      if(recording){
        recorded.current.push({time:(performance.now()-startT.current)/1000,keyframes:kf});
        setFrameCount(recorded.current.length);
      }
    });
    poseRef.current=pose; return pose;
  }

  async function startWebcam(){
    if(!mpReady){setStatus('MediaPipe loading…');return;}
    const canvas=canvasRef.current;
    canvas.width=canvasW;canvas.height=canvasH;
    try{
      const stream=await navigator.mediaDevices.getUserMedia({video:{width:canvasW,height:canvasH}});
      videoRef.current.srcObject=stream;videoRef.current.play();
      const pose=initPose(videoRef.current,canvas);if(!pose)return;
      if(window.Camera){
        camRef.current=new window.Camera(videoRef.current,{onFrame:async()=>{await pose.send({image:videoRef.current});},width:canvasW,height:canvasH});
        camRef.current.start();setLive(true);setStatus('✓ Live body mocap running');
      }
    }catch(e){setStatus('Camera error: '+e.message);}
  }

  async function processVideo(file){
    if(!mpReady){setStatus('MediaPipe loading…');return;}
    setVideoSrc(URL.createObjectURL(file));
    setTimeout(async()=>{
      const video=videoRef.current,canvas=canvasRef.current;
      canvas.width=canvasW;canvas.height=canvasH;
      const pose=initPose(video,canvas);if(!pose)return;
      recorded.current=[];setRecording(true);
      const duration=video.duration,step=1/fps;let t=0;
      setStatus('Processing video…');
      while(t<=duration){
        video.currentTime=t;
        await new Promise(res=>video.addEventListener('seeked',res,{once:true}));
        await pose.send({image:video});
        setProgress(Math.round(t/duration*100));
        t+=step;
      }
      setRecording(false);buildMotion();
    },500);
  }

  function buildMotion(){
    const bones=[...new Set([...Object.values(POSE_TO_SPX),'hips','spine'])];
    const motion={version:'1.0',format:'spxmotion',name:'video_mocap',fps,
      duration:recorded.current.length/fps,canvasW,canvasH,bones,frames:recorded.current};
    const b=new Blob([JSON.stringify(motion,null,2)],{type:'application/json'});
    const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='video_mocap.spxmotion';a.click();
    onMotionReady&&onMotionReady(motion);
    setStatus(`✓ video_mocap.spxmotion downloaded (${recorded.current.length} frames)`);
  }

  function startRecord(){recorded.current=[];startT.current=performance.now();setRecording(true);setFrameCount(0);setStatus('Recording…');}
  function stopRecord(){setRecording(false);setStatus(`${recorded.current.length} frames recorded`);if(recorded.current.length)buildMotion();}
  function stopAll(){camRef.current?.stop();if(videoRef.current?.srcObject)videoRef.current.srcObject.getTracks().forEach(t=>t.stop());setLive(false);setRecording(false);setStatus('Stopped');}

  return(
    <div style={S.root}>
      <div style={S.h2}>🎬 VIDEO BODY MOCAP</div>
      <div style={S.sec}>
        <div style={S.stat}>{mpReady?'✓ MediaPipe Pose ready':'⏳ Loading MediaPipe…'}</div>
        <video ref={videoRef} src={videoSrc} style={{display:'none'}} crossOrigin="anonymous" playsInline muted/>
        <canvas ref={canvasRef} style={S.canvas}/>
      </div>
      <div style={S.sec}>
        <button style={S.btn} onClick={startWebcam}>📷 Live Webcam</button>
        <label style={S.btn}>
          📁 Upload MP4
          <input type="file" accept="video/*" style={{display:'none'}} onChange={e=>e.target.files[0]&&processVideo(e.target.files[0])}/>
        </label>
      </div>
      {live&&(recording
        ?<button style={S.btnRed} onClick={stopRecord}>⏹ Stop + Export</button>
        :<button style={S.btnO} onClick={startRecord}>⏺ Record</button>
      )}
      {live&&<button style={S.btn} onClick={stopAll}>✕ Stop All</button>}
      {progress>0&&progress<100&&<div style={{background:T.panel,borderRadius:4,padding:4,marginTop:8}}><div style={S.bar(progress)}/><div style={{fontSize:10,color:T.teal,marginTop:4}}>{progress}%</div></div>}
      {recording&&<div style={S.stat}>Frames: {frameCount}</div>}
      {status&&<div style={{...S.stat,marginTop:8}}>{status}</div>}
    </div>
  );
}
"""

# ════════════════════════════════════════════════════════════
# 3. FACE MOCAP PANEL
# ════════════════════════════════════════════════════════════
FILES[f"{MOCAP}/FaceMocapPanel.jsx"] = r"""
import React, { useState, useRef, useEffect } from 'react';

const T={bg:"#06060f",panel:"#0d0d1a",border:"#1a1a2e",teal:"#00ffc8",orange:"#FF6600",text:"#e0e0e0",muted:"#aaa",font:"JetBrains Mono,monospace"};
const S={
  root:{background:T.bg,color:T.text,fontFamily:T.font,padding:16,height:"100%",overflowY:"auto"},
  h2:{color:T.teal,fontSize:14,marginBottom:12,letterSpacing:1},
  lbl:{fontSize:11,color:T.muted,display:"block",marginBottom:4},
  inp:{width:"100%",background:T.panel,border:"1px solid "+T.border,color:T.text,padding:"4px 8px",borderRadius:4,fontFamily:T.font,fontSize:11,marginBottom:8,boxSizing:"border-box"},
  btn:{background:T.teal,color:T.bg,border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnO:{background:T.orange,color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnRed:{background:"#cc2200",color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  sec:{background:T.panel,border:"1px solid "+T.border,borderRadius:6,padding:12,marginBottom:12},
  stat:{fontSize:11,color:T.teal,marginBottom:4},
  bar:{background:"#1a1a2e",borderRadius:3,height:8,marginBottom:4},
  barFill:(v)=>({width:`${Math.round(Math.max(0,Math.min(1,v))*100)}%`,height:"100%",background:T.teal,borderRadius:3}),
  canvas:{width:"100%",borderRadius:6,border:"1px solid "+T.border,background:"#000",display:"block"},
};

function dist(a,b){ if(!a||!b)return 0; return Math.sqrt((a.x-b.x)**2+(a.y-b.y)**2+((a.z||0)-(b.z||0))**2); }

function extractFaceParams(lm){
  const jawOpen  = Math.min(1, dist(lm[13],lm[14])*15);
  const eyeL     = Math.min(1, dist(lm[159],lm[145])*12);
  const eyeR     = Math.min(1, dist(lm[386],lm[374])*12);
  const browL    = Math.max(0, 0.5-(lm[105].y-lm[159].y)*10);
  const browR    = Math.max(0, 0.5-(lm[334].y-lm[386].y)*10);
  const mouthW   = dist(lm[61],lm[291]);
  const smile    = Math.min(1,(mouthW-0.12)*10);
  const headYaw  = (lm[4].x-0.5)*2;
  const headPitch= (lm[4].y-(lm[152]?.y||0.7))*3-0.6;
  const headRoll = ((lm[61]?.y||0.5)-(lm[291]?.y||0.5))*5;
  return {jawOpen,eyeL,eyeR,browL,browR,smile,headYaw,headPitch,headRoll};
}

export default function FaceMocapPanel({ onFaceParams, onMotionReady }) {
  const [mpReady,setMpReady]=useState(false);
  const [live,setLive]=useState(false);
  const [recording,setRecording]=useState(false);
  const [params,setParams]=useState({});
  const [fps,setFps]=useState(30);
  const [frameCount,setFrameCount]=useState(0);
  const [status,setStatus]=useState('');
  const videoRef=useRef(null);
  const canvasRef=useRef(null);
  const meshRef=useRef(null);
  const camRef=useRef(null);
  const recorded=useRef([]);
  const startT=useRef(0);

  useEffect(()=>{
    if(window.FaceMesh){setMpReady(true);return;}
    const s=document.createElement('script');
    s.src='https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js';
    s.crossOrigin='anonymous';s.onload=()=>setMpReady(true);
    document.head.appendChild(s);
  },[]);

  function initFaceMesh(videoEl,canvasEl){
    if(!window.FaceMesh){setStatus('FaceMesh not loaded');return null;}
    const fm=new window.FaceMesh({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${f}`});
    fm.setOptions({maxNumFaces:1,refineLandmarks:true,minDetectionConfidence:0.5,minTrackingConfidence:0.5});
    fm.onResults(results=>{
      const ctx=canvasEl.getContext('2d');
      ctx.clearRect(0,0,canvasEl.width,canvasEl.height);
      ctx.drawImage(results.image,0,0,canvasEl.width,canvasEl.height);
      if(!results.multiFaceLandmarks?.[0]) return;
      const lm=results.multiFaceLandmarks[0];
      ctx.fillStyle='#00ffc8';
      lm.forEach(p=>{ctx.beginPath();ctx.arc(p.x*canvasEl.width,p.y*canvasEl.height,1,0,Math.PI*2);ctx.fill();});
      const fp=extractFaceParams(lm);
      setParams(fp);
      onFaceParams&&onFaceParams(fp);
      if(recording){
        recorded.current.push({time:(performance.now()-startT.current)/1000,params:{...fp}});
        setFrameCount(recorded.current.length);
      }
    });
    meshRef.current=fm;return fm;
  }

  async function startLive(){
    if(!mpReady){setStatus('MediaPipe loading…');return;}
    const canvas=canvasRef.current;canvas.width=480;canvas.height=360;
    try{
      const stream=await navigator.mediaDevices.getUserMedia({video:{width:480,height:360}});
      videoRef.current.srcObject=stream;videoRef.current.play();
      const fm=initFaceMesh(videoRef.current,canvas);if(!fm)return;
      if(window.Camera){
        camRef.current=new window.Camera(videoRef.current,{onFrame:async()=>{await fm.send({image:videoRef.current});},width:480,height:360});
        camRef.current.start();setLive(true);setStatus('✓ Face mocap live');
      } else {
        // Fallback: manual frame loop
        const loop=async()=>{if(!live)return;await fm.send({image:videoRef.current});requestAnimationFrame(loop);};
        requestAnimationFrame(loop);setLive(true);setStatus('✓ Face mocap live (fallback mode)');
      }
    }catch(e){setStatus('Camera error: '+e.message);}
  }

  function stopLive(){camRef.current?.stop();if(videoRef.current?.srcObject)videoRef.current.srcObject.getTracks().forEach(t=>t.stop());setLive(false);setStatus('Stopped');}
  function startRecord(){recorded.current=[];startT.current=performance.now();setRecording(true);setStatus('Recording…');setFrameCount(0);}
  function stopRecord(){setRecording(false);setStatus(`${recorded.current.length} frames recorded`);if(recorded.current.length)exportMotion();}

  function exportMotion(){
    const duration=recorded.current[recorded.current.length-1]?.time||0;
    const frames=recorded.current.map(r=>({
      time:r.time,
      keyframes:{
        face_jaw:    {x:0,y:0,rotation:r.params.jawOpen*20,scale:1},
        face_eye_l:  {x:0,y:0,rotation:0,scale:Math.max(0.05,r.params.eyeL)},
        face_eye_r:  {x:0,y:0,rotation:0,scale:Math.max(0.05,r.params.eyeR)},
        face_brow_l: {x:0,y:-r.params.browL*10,rotation:0,scale:1},
        face_brow_r: {x:0,y:-r.params.browR*10,rotation:0,scale:1},
        face_smile:  {x:0,y:0,rotation:r.params.smile*10,scale:1},
        head:        {x:320+r.params.headYaw*80,y:180-r.params.headPitch*60,rotation:r.params.headRoll*20,scale:1},
      }
    }));
    const motion={version:'1.0',format:'spxmotion',name:'face_mocap',fps,duration,
      canvasW:640,canvasH:480,
      bones:['face_jaw','face_eye_l','face_eye_r','face_brow_l','face_brow_r','face_smile','head'],frames};
    const b=new Blob([JSON.stringify(motion,null,2)],{type:'application/json'});
    const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='face_mocap.spxmotion';a.click();
    onMotionReady&&onMotionReady(motion);
    setStatus(`✓ face_mocap.spxmotion exported (${frames.length} frames)`);
  }

  const pBar=(label,val)=>(
    <div key={label}>
      <div style={S.lbl}>{label}: {typeof val==='number'?val.toFixed(3):val}</div>
      {typeof val==='number'&&<div style={S.bar}><div style={S.barFill(Math.abs(val))}/></div>}
    </div>
  );

  return(
    <div style={S.root}>
      <div style={S.h2}>😶 FACE MOCAP</div>
      <div style={S.sec}>
        <div style={S.stat}>{mpReady?'✓ FaceMesh ready':'⏳ Loading…'}</div>
        <video ref={videoRef} style={{display:'none'}} playsInline muted/>
        <canvas ref={canvasRef} style={S.canvas}/>
      </div>
      <div style={S.sec}>
        {!live
          ?<button style={S.btn} onClick={startLive}>📷 Start Face Mocap</button>
          :<button style={S.btnRed} onClick={stopLive}>✕ Stop</button>
        }
        {live&&(!recording
          ?<button style={S.btnO} onClick={startRecord}>⏺ Record</button>
          :<button style={S.btnRed} onClick={stopRecord}>⏹ Stop + Export</button>
        )}
      </div>
      {Object.keys(params).length>0&&(
        <div style={S.sec}>
          <div style={S.lbl}>Live Parameters</div>
          {pBar('Jaw Open',   params.jawOpen)}
          {pBar('Eye L',      params.eyeL)}
          {pBar('Eye R',      params.eyeR)}
          {pBar('Brow L',     params.browL)}
          {pBar('Brow R',     params.browR)}
          {pBar('Smile',      params.smile)}
          {pBar('Head Yaw',   params.headYaw)}
          {pBar('Head Pitch', params.headPitch)}
          {pBar('Head Roll',  params.headRoll)}
        </div>
      )}
      {recording&&<div style={S.stat}>Frames: {frameCount}</div>}
      {status&&<div style={{...S.stat,marginTop:4}}>{status}</div>}
    </div>
  );
}
"""

# ════════════════════════════════════════════════════════════
# 4. SPXMOTION PLAYER PANEL (import + play .spxmotion in puppet)
# ════════════════════════════════════════════════════════════
FILES[f"{COMP}/SPXMotionPlayerPanel.jsx"] = r"""
import React, { useState, useRef } from 'react';
import SPXMotionImporter from '../pipeline/SPXMotionImporter';

const T={bg:"#06060f",panel:"#0d0d1a",border:"#1a1a2e",teal:"#00ffc8",orange:"#FF6600",text:"#e0e0e0",muted:"#aaa",font:"JetBrains Mono,monospace"};
const S={
  root:{background:T.bg,color:T.text,fontFamily:T.font,padding:16,height:"100%",overflowY:"auto"},
  h2:{color:T.teal,fontSize:14,marginBottom:12,letterSpacing:1},
  lbl:{fontSize:11,color:T.muted,display:"block",marginBottom:4},
  inp:{width:"100%",background:T.panel,border:"1px solid "+T.border,color:T.text,padding:"4px 8px",borderRadius:4,fontFamily:T.font,fontSize:11,marginBottom:8,boxSizing:"border-box"},
  btn:{background:T.teal,color:T.bg,border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnO:{background:T.orange,color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnRed:{background:"#cc2200",color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  sec:{background:T.panel,border:"1px solid "+T.border,borderRadius:6,padding:12,marginBottom:12},
  stat:{fontSize:11,color:T.teal,marginBottom:4},
  progress:(p)=>({width:`${p*100}%`,height:4,background:T.teal,borderRadius:2,transition:"width .05s"}),
  track:{background:"#1a1a2e",borderRadius:4,height:4,marginBottom:8,cursor:"pointer",position:"relative"},
};

export default function SPXMotionPlayerPanel({ onFrame }) {
  const [loaded,setLoaded]=useState(null);
  const [playing,setPlaying]=useState(false);
  const [loop,setLoop]=useState(true);
  const [speed,setSpeed]=useState(1.0);
  const [progress,setProgress]=useState(0);
  const [currentTime,setCurrentTime]=useState(0);
  const [status,setStatus]=useState('');
  const importerRef=useRef(new SPXMotionImporter());
  const raf=useRef(null);
  const startT=useRef(0);
  const pausedAt=useRef(0);

  async function loadFile(file){
    try{
      const motion=await importerRef.current.loadFromFile(file);
      setLoaded({name:motion.name,duration:motion.duration,fps:motion.fps,bones:motion.bones.length,frames:motion.frames.length});
      setStatus(`✓ Loaded: ${motion.name} (${motion.duration.toFixed(2)}s, ${motion.bones.length} bones)`);
      setProgress(0);setCurrentTime(0);
    }catch(e){setStatus('Error: '+e.message);}
  }

  function startPlay(){
    const imp=importerRef.current;
    if(!imp.motion){setStatus('No motion loaded');return;}
    setPlaying(true);
    if(loop){
      imp.loop(kf=>{
        onFrame&&onFrame(kf);
        const elapsed=(performance.now()-startT.current)/1000*speed;
        const t=((elapsed%imp.duration)+imp.duration)%imp.duration;
        setProgress(t/imp.duration);setCurrentTime(t);
      });
    } else {
      imp.play(kf=>{
        onFrame&&onFrame(kf);
        const elapsed=(performance.now()-startT.current)/1000*speed;
        setProgress(Math.min(1,elapsed/imp.duration));setCurrentTime(Math.min(elapsed,imp.duration));
      },()=>{setPlaying(false);setProgress(1);setStatus('Playback complete');});
    }
    startT.current=performance.now()-pausedAt.current*1000/speed;
    setStatus('Playing…');
  }

  function stopPlay(){
    importerRef.current.stop();
    pausedAt.current=currentTime;
    setPlaying(false);setStatus('Paused');
  }

  function resetPlay(){
    importerRef.current.stop();
    setPlaying(false);setProgress(0);setCurrentTime(0);pausedAt.current=0;setStatus('Reset');
  }

  function seekTo(e){
    if(!loaded)return;
    const rect=e.currentTarget.getBoundingClientRect();
    const p=(e.clientX-rect.left)/rect.width;
    const t=p*loaded.duration;
    pausedAt.current=t;setCurrentTime(t);setProgress(p);
    const kf=importerRef.current.getFrameAt(t);
    onFrame&&onFrame(kf);
  }

  return(
    <div style={S.root}>
      <div style={S.h2}>🎭 SPXMOTION PLAYER</div>
      <div style={S.sec}>
        <label style={S.btn}>
          📁 Load .spxmotion
          <input type="file" accept=".spxmotion,.json" style={{display:'none'}}
            onChange={e=>e.target.files[0]&&loadFile(e.target.files[0])}/>
        </label>
        {status&&<div style={{...S.stat,marginTop:4}}>{status}</div>}
      </div>

      {loaded&&<>
        <div style={S.sec}>
          <div style={S.stat}>Name: {loaded.name}</div>
          <div style={S.stat}>Duration: {loaded.duration.toFixed(2)}s @ {loaded.fps}fps</div>
          <div style={S.stat}>Bones: {loaded.bones} | Frames: {loaded.frames}</div>
        </div>

        <div style={S.sec}>
          <div style={S.track} onClick={seekTo}>
            <div style={S.progress(progress)}/>
          </div>
          <div style={{fontSize:10,color:T.muted,marginBottom:8}}>
            {currentTime.toFixed(2)}s / {loaded.duration.toFixed(2)}s
          </div>
          {!playing
            ?<button style={S.btn} onClick={startPlay}>▶ Play</button>
            :<button style={S.btnRed} onClick={stopPlay}>⏸ Pause</button>
          }
          <button style={S.btnO} onClick={resetPlay}>⏮ Reset</button>
          <label style={{...S.lbl,cursor:'pointer',marginTop:8}}>
            <input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/> Loop
          </label>
          <label style={S.lbl}>Speed: {speed.toFixed(2)}x</label>
          <input style={S.inp} type="range" min={0.1} max={3} step={0.05} value={speed} onChange={e=>setSpeed(+e.target.value)}/>
        </div>
      </>}

      <div style={S.sec}>
        <div style={{fontSize:10,color:'#888',lineHeight:1.7}}>
          .spxmotion files are generated by:<br/>
          • SPX Mesh Editor → Export to Puppet button<br/>
          • Video Body Mocap panel<br/>
          • Face Mocap panel<br/>
          Compatible with all SPX Puppet bone names
        </div>
      </div>
    </div>
  );
}
"""

# ════════════════════════════════════════════════════════════
# 5. PUPPET 2D STYLE EXPORT PANEL
# ════════════════════════════════════════════════════════════
FILES[f"{COMP}/Puppet2DStylePanel.jsx"] = r"""
import React, { useState, useRef, useEffect } from 'react';

const T={bg:"#06060f",panel:"#0d0d1a",border:"#1a1a2e",teal:"#00ffc8",orange:"#FF6600",text:"#e0e0e0",muted:"#aaa",font:"JetBrains Mono,monospace"};
const S={
  root:{background:T.bg,color:T.text,fontFamily:T.font,padding:16,height:"100%",overflowY:"auto"},
  h2:{color:T.teal,fontSize:14,marginBottom:12,letterSpacing:1},
  h3:{color:T.orange,fontSize:12,marginBottom:8,marginTop:8},
  lbl:{fontSize:11,color:T.muted,display:"block",marginBottom:4},
  inp:{width:"100%",background:T.panel,border:"1px solid "+T.border,color:T.text,padding:"4px 8px",borderRadius:4,fontFamily:T.font,fontSize:11,marginBottom:8,boxSizing:"border-box"},
  btn:{background:T.teal,color:T.bg,border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnO:{background:T.orange,color:"#fff",border:"none",borderRadius:4,padding:"7px 16px",fontFamily:T.font,fontSize:12,fontWeight:700,cursor:"pointer",marginRight:8,marginBottom:8},
  btnSm:{background:T.panel,color:T.teal,border:"1px solid "+T.teal,borderRadius:4,padding:"3px 10px",fontFamily:T.font,fontSize:10,cursor:"pointer",marginRight:4,marginBottom:4},
  sec:{background:T.panel,border:"1px solid "+T.border,borderRadius:6,padding:12,marginBottom:12},
  stat:{fontSize:11,color:T.teal,marginBottom:4},
  canvas:{width:"100%",borderRadius:6,border:"2px solid "+T.border,display:"block",background:"#000"},
};

const STYLES = {
  "Anime Standard":      {headScale:0.85,limbScale:1.25,inkOutline:true,color:"#00ffc8",bgColor:"#06060f"},
  "Manga B&W":           {headScale:0.88,limbScale:1.2, inkOutline:true,color:"#ffffff",bgColor:"#000000",grayscale:true,speedLines:true},
  "Marvel What If":      {headScale:1.05,limbScale:1.15,inkOutline:true,color:"#FF6600",bgColor:"#fffef0",halftone:true},
  "Spider-Verse":        {headScale:1.0, limbScale:1.0, inkOutline:true,color:"#ff00ff",bgColor:"#fffef0",halftone:true,frameSkip:3},
  "90s Saturday Morning":{headScale:1.1, limbScale:1.05,inkOutline:true,color:"#ffaa00",bgColor:"#06060f",limitedPalette:true},
  "Classic Cartoon":     {headScale:1.3, limbScale:1.1, inkOutline:true,color:"#ffffff",bgColor:"#1a0a00",rubberLimbs:true},
  "Studio Ghibli":       {headScale:1.05,limbScale:0.95,inkOutline:false,color:"#88cc88",bgColor:"#334422"},
  "Chibi SD":            {headScale:1.8, limbScale:0.55,inkOutline:true,color:"#ff88cc",bgColor:"#220033"},
  "Synthwave Retro":     {headScale:1.0, limbScale:1.0, inkOutline:false,color:"#00ffc8",bgColor:"#050510",neonGlow:true},
  "Noir Cinematic":      {headScale:1.0, limbScale:1.0, inkOutline:true,color:"#ffffff",bgColor:"#000000",grayscale:true,highContrast:true},
  "Fleischer Rubber Hose":{headScale:1.4,limbScale:1.0, inkOutline:true,color:"#443322",bgColor:"#f5e6b0",rubberLimbs:true},
  "CalArts / Adventure Time":{headScale:1.15,limbScale:1.0,inkOutline:true,color:"#ff6600",bgColor:"#ffffff",wobbleLines:true},
  "Wayang Kulit Shadow": {headScale:1.0, limbScale:1.0, inkOutline:false,color:"#000000",bgColor:"#ff6600",silhouette:true},
  "South Park Cutout":   {headScale:1.2, limbScale:0.8, inkOutline:true,color:"#ff4400",bgColor:"#87ceeb",staticLimbs:true},
  "UPA Flat 50s":        {headScale:0.9, limbScale:0.85,inkOutline:true,color:"#cc4422",bgColor:"#f0e8d0",geometricShapes:true},
  "Soviet Soyuzmultfilm":{headScale:1.05,limbScale:0.95,inkOutline:false,color:"#8899aa",bgColor:"#1a2a1a",painterly:true,filmGrain:true},
  "Adult Swim Surreal":  {headScale:1.05,limbScale:1.0, inkOutline:true,color:"#00ff88",bgColor:"#050510",vhsDistort:true,filmGrain:true},
  "Moebius / Heavy Metal":{headScale:0.88,limbScale:1.1,inkOutline:true,color:"#cc9944",bgColor:"#f8f4e8",crosshatch:true},
  "Isometric Pixel":     {headScale:1.0, limbScale:1.0, inkOutline:false,color:"#00ffc8",bgColor:"#0d0d1a",pixelGrid:4},
  "8-Bit Pixel":         {headScale:1.0, limbScale:1.0, inkOutline:false,color:"#00ff00",bgColor:"#000000",pixelGrid:8},
};

const SKELETON = {
  head:{x:320,y:80}, neck:{x:320,y:110}, chest:{x:320,y:155}, spine:{x:320,y:185}, hips:{x:320,y:220},
  l_shoulder:{x:290,y:130}, l_upper_arm:{x:265,y:155}, l_forearm:{x:248,y:185}, l_hand:{x:240,y:210},
  r_shoulder:{x:350,y:130}, r_upper_arm:{x:375,y:155}, r_forearm:{x:392,y:185}, r_hand:{x:400,y:210},
  l_thigh:{x:305,y:255}, l_shin:{x:300,y:295}, l_foot:{x:295,y:325},
  r_thigh:{x:335,y:255}, r_shin:{x:340,y:295}, r_foot:{x:345,y:325},
};

const CONNECTIONS=[
  ["head","neck"],["neck","chest"],["chest","spine"],["spine","hips"],
  ["chest","l_shoulder"],["l_shoulder","l_upper_arm"],["l_upper_arm","l_forearm"],["l_forearm","l_hand"],
  ["chest","r_shoulder"],["r_shoulder","r_upper_arm"],["r_upper_arm","r_forearm"],["r_forearm","r_hand"],
  ["hips","l_thigh"],["l_thigh","l_shin"],["l_shin","l_foot"],
  ["hips","r_thigh"],["r_thigh","r_shin"],["r_shin","r_foot"],
];

function drawStyle(ctx,kf,sp,w,h,t=0){
  ctx.clearRect(0,0,w,h);
  // Background
  if(sp.neonGlow){ctx.fillStyle="#050510";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#220044";ctx.lineWidth=0.5;for(let i=0;i<w;i+=20){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,h);ctx.stroke();}for(let j=0;j<h;j+=20){ctx.beginPath();ctx.moveTo(0,j);ctx.lineTo(w,j);ctx.stroke();}}
  else if(sp.halftone){ctx.fillStyle="#fffef0";ctx.fillRect(0,0,w,h);ctx.fillStyle="#e0d8c0";for(let i=0;i<w;i+=8)for(let j=0;j<h;j+=8){ctx.beginPath();ctx.arc(i,j,1.5,0,Math.PI*2);ctx.fill();}}
  else if(sp.vhsDistort){ctx.fillStyle="#050510";ctx.fillRect(0,0,w,h);ctx.globalAlpha=0.12;for(let y=0;y<h;y+=3){ctx.fillStyle=y%6===0?"#ffffff":"#000";ctx.fillRect(0,y,w,1);}ctx.globalAlpha=1;}
  else if(sp.silhouette){const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#2a1500");bg.addColorStop(0.5,sp.bgColor||"#ff6600");bg.addColorStop(1,"#2a1500");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);}
  else{ctx.fillStyle=sp.bgColor||"#06060f";ctx.fillRect(0,0,w,h);}
  if(sp.filmGrain){ctx.globalAlpha=0.04;for(let i=0;i<300;i++){ctx.fillStyle="#fff";ctx.fillRect(Math.random()*w,Math.random()*h,1,1);}ctx.globalAlpha=1;}
  if(sp.speedLines){ctx.strokeStyle="rgba(255,255,255,0.06)";ctx.lineWidth=1;for(let i=0;i<20;i++){ctx.beginPath();ctx.moveTo(w/2,h/2);const a=i/20*Math.PI*2;ctx.lineTo(w/2+Math.cos(a)*w,h/2+Math.sin(a)*h);ctx.stroke();}}

  const col=sp.grayscale?"#aaaaaa":(sp.color||"#00ffc8");
  const lw=sp.inkOutline?3:2;

  if(sp.rubberLimbs){
    CONNECTIONS.forEach(([a,b])=>{
      const pa=kf[a],pb=kf[b];if(!pa||!pb)return;
      const mx=(pa.x+pb.x)/2+Math.sin(t*3+pa.x)*8,my=(pa.y+pb.y)/2+Math.cos(t*3+pa.y)*8;
      ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.quadraticCurveTo(mx,my,pb.x,pb.y);
      if(sp.neonGlow){ctx.shadowBlur=10;ctx.shadowColor=col;}
      ctx.strokeStyle=col;ctx.lineWidth=4;ctx.stroke();ctx.shadowBlur=0;
    });
  } else if(sp.silhouette){
    ctx.fillStyle="#000000";
    Object.values(kf).forEach(pos=>{ctx.beginPath();ctx.arc(pos.x,pos.y,8,0,Math.PI*2);ctx.fill();});
    CONNECTIONS.forEach(([a,b])=>{const pa=kf[a],pb=kf[b];if(!pa||!pb)return;ctx.strokeStyle="#000";ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();});
  } else if(!sp.staticLimbs){
    if(sp.inkOutline){CONNECTIONS.forEach(([a,b])=>{const pa=kf[a],pb=kf[b];if(!pa||!pb)return;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.strokeStyle="#000";ctx.lineWidth=lw+2;ctx.stroke();});}
    CONNECTIONS.forEach(([a,b])=>{
      const pa=kf[a],pb=kf[b];if(!pa||!pb)return;
      ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);
      if(sp.neonGlow){ctx.shadowBlur=8;ctx.shadowColor=col;}
      ctx.strokeStyle=sp.grayscale&&sp.highContrast?"#fff":col;ctx.lineWidth=lw;ctx.stroke();ctx.shadowBlur=0;
    });
  } else {
    // Static limbs — body only
    ["chest","spine","hips","l_shoulder","r_shoulder"].forEach(b=>{if(kf[b]){ctx.beginPath();ctx.arc(kf[b].x,kf[b].y,6,0,Math.PI*2);ctx.fillStyle=col;ctx.fill();}});
  }

  // Joints
  Object.entries(kf).forEach(([bone,pos])=>{
    const r=bone==="head"?(sp.headScale||1)*14:4;
    ctx.beginPath();ctx.arc(pos.x,pos.y,r,0,Math.PI*2);
    if(bone==="head"){ctx.fillStyle=sp.bgColor||"#06060f";ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.stroke();}
    else{if(sp.neonGlow){ctx.shadowBlur=6;ctx.shadowColor=col;}ctx.fillStyle=col;ctx.fill();ctx.shadowBlur=0;}
  });

  if(sp.pixelGrid){
    const snap=(v,g)=>Math.round(v/g)*g;
    ctx.globalAlpha=0.3;
    ctx.strokeStyle=col;ctx.lineWidth=0.5;
    for(let x=0;x<w;x+=sp.pixelGrid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}
    for(let y=0;y<h;y+=sp.pixelGrid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
    ctx.globalAlpha=1;
  }
  ctx.fillStyle="rgba(0,255,200,0.5)";ctx.font="10px JetBrains Mono,monospace";
  ctx.fillText(Object.keys(STYLES).find(k=>STYLES[k]===sp)||"Style",8,h-8);
}

export default function Puppet2DStylePanel({ liveKeyframes }) {
  const canvasRef=useRef(null);
  const [style,setStyle]=useState("Anime Standard");
  const [playing,setPlaying]=useState(true);
  const [t,setT]=useState(0);
  const raf=useRef(null);
  const lastT=useRef(0);
  const tRef=useRef(0);
  const KF=liveKeyframes||SKELETON;

  useEffect(()=>{
    const tick=(now)=>{
      const dt=Math.min((now-lastT.current)/1000,0.05);
      lastT.current=now;
      if(playing) tRef.current+=dt;
      const canvas=canvasRef.current;if(!canvas)return;
      canvas.width=640;canvas.height=400;
      const sp=STYLES[style]||STYLES["Anime Standard"];
      // Animate skeleton slightly
      const animKF={};
      Object.entries(KF).forEach(([b,v])=>{
        animKF[b]={...v};
        if(b==="head")animKF[b].y=v.y+Math.sin(tRef.current*1.5)*3;
        if(b.includes("hand"))animKF[b].x=v.x+Math.sin(tRef.current*2+(b.includes("l")?0:Math.PI))*8;
      });
      drawStyle(canvas.getContext("2d"),animKF,sp,640,400,tRef.current);
      raf.current=requestAnimationFrame(tick);
    };
    raf.current=requestAnimationFrame(tick);
    return()=>cancelAnimationFrame(raf.current);
  },[style,playing,liveKeyframes]);

  function exportFrame(){
    const canvas=canvasRef.current;if(!canvas)return;
    const a=document.createElement("a");a.href=canvas.toDataURL("image/png");
    a.download=`puppet_${style.replace(/ /g,"_")}.png`;a.click();
  }

  return(
    <div style={S.root}>
      <div style={S.h2}>🎨 2D STYLE EXPORT</div>
      <div style={S.sec}>
        <label style={S.lbl}>Animation Style ({Object.keys(STYLES).length} available)</label>
        <div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:8}}>
          {Object.keys(STYLES).map(s=>(
            <button key={s} style={{...S.btnSm,background:style===s?T.teal:T.panel,color:style===s?T.bg:T.teal}} onClick={()=>setStyle(s)}>
              {s}
            </button>
          ))}
        </div>
      </div>
      <canvas ref={canvasRef} style={S.canvas}/>
      <div style={{marginTop:8}}>
        <button style={S.btn} onClick={()=>setPlaying(!playing)}>{playing?"⏸ Pause":"▶ Play"}</button>
        <button style={S.btnO} onClick={exportFrame}>💾 Export Frame</button>
      </div>
      <div style={S.sec}>
        <div style={{fontSize:10,color:"#888",lineHeight:1.7}}>
          Styles apply to live puppet output in real-time<br/>
          Export any frame as PNG for storyboarding<br/>
          Connect liveKeyframes prop to drive from puppet rig
        </div>
      </div>
    </div>
  );
}
"""

# Write all files
print("Writing files...")
for path, content in FILES.items():
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content.strip())
    short = path.replace(f"{REPO}/","")
    print(f"  ✓ {short}")

print(f"\n✅ {len(FILES)} files written to SPX Puppet")
print("Run: npm run build && git add -A && git commit -m 'feat: SPXMotionImporter, VideoMocap, FaceMocap, MotionPlayer, 2D Style Export' && git push")
