/**
 * SPXMotionImporter — SPX Puppet
 * Loads .spxmotion files and drives puppet bone keyframes
 * .spxmotion is generated by SPX Mesh Editor's ExportToPuppetButton
 */
export class SPXMotionImporter {
  constructor() {
    this.motion=null; this.playing=false; this.startTime=null;
    this.onFrame=null; this.onComplete=null; this._raf=null;
  }

  async loadFromFile(file) {
    return new Promise((resolve,reject)=>{
      const r=new FileReader();
      r.onload=e=>{
        try{ const d=JSON.parse(e.target.result); this.load(d); resolve(d); }
        catch(err){ reject(new Error('Invalid .spxmotion: '+err.message)); }
      };
      r.onerror=()=>reject(new Error('File read error'));
      r.readAsText(file);
    });
  }

  load(data) {
    if(data.format!=='spxmotion') throw new Error('Not a .spxmotion file');
    this.motion=data; this.playing=false;
    this._raf&&cancelAnimationFrame(this._raf);
  }

  getFrameAt(time) {
    if(!this.motion) return {};
    const {frames,duration}=this.motion;
    const t=((time%duration)+duration)%duration;
    let lo=0,hi=frames.length-1;
    while(lo<hi-1){ const mid=(lo+hi)>>1; if(frames[mid].time<=t) lo=mid; else hi=mid; }
    const fA=frames[lo], fB=frames[Math.min(hi,frames.length-1)];
    if(!fB||fA===fB) return{...fA.keyframes};
    const span=fB.time-fA.time, alpha=span>0?(t-fA.time)/span:0;
    const result={};
    this.motion.bones.forEach(bone=>{
      const a=fA.keyframes[bone]||{}, b=fB.keyframes[bone]||{};
      result[bone]={
        x:       lerp(a.x||0,      b.x||0,      alpha),
        y:       lerp(a.y||0,      b.y||0,      alpha),
        rotation:lerpAngle(a.rotation||0, b.rotation||0, alpha),
        scale:   lerp(a.scale||1,  b.scale||1,  alpha),
      };
    });
    return result;
  }

  play(onFrame,onComplete) {
    if(!this.motion) return;
    this.onFrame=onFrame||this.onFrame;
    this.onComplete=onComplete||this.onComplete;
    this.playing=true; this.startTime=performance.now();
    const tick=(now)=>{
      if(!this.playing) return;
      const elapsed=(now-this.startTime)/1000;
      this.onFrame&&this.onFrame(this.getFrameAt(elapsed),elapsed);
      if(elapsed>=this.motion.duration){ this.playing=false; this.onComplete&&this.onComplete(); return; }
      this._raf=requestAnimationFrame(tick);
    };
    this._raf=requestAnimationFrame(tick);
  }

  loop(onFrame) {
    if(!this.motion) return;
    this.onFrame=onFrame; this.playing=true; this.startTime=performance.now();
    const tick=(now)=>{
      if(!this.playing) return;
      const elapsed=(now-this.startTime)/1000;
      this.onFrame&&this.onFrame(this.getFrameAt(elapsed),elapsed);
      this._raf=requestAnimationFrame(tick);
    };
    this._raf=requestAnimationFrame(tick);
  }

  stop(){ this.playing=false; this._raf&&cancelAnimationFrame(this._raf); }
  get duration(){ return this.motion?.duration||0; }
  get fps()     { return this.motion?.fps||30; }
  get bones()   { return this.motion?.bones||[]; }
  get name()    { return this.motion?.name||''; }
}

function lerp(a,b,t){ return a+(b-a)*t; }
function lerpAngle(a,b,t){ let d=((b-a)%360+540)%360-180; return a+d*t; }
export default SPXMotionImporter;